class Manufacturer:
    def __init__(self, name):
        self.name = name


H_K = Manufacturer("Heckler & Koch")
FN = Manufacturer("FN Herstal")
SIG = Manufacturer("SIG Sauer")
Beretta = Manufacturer("Beretta")
IWI = Manufacturer("Israel Weapon Industries")
Colt_FN = Manufacturer("Colt/FN USA")
DanielDefense = Manufacturer("Daniel Defense")
Glock = Manufacturer("Glock")
KA_BAR = Manufacturer("KA-BAR")
Ontario = Manufacturer("Ontario Knife Company")
Gerber = Manufacturer("Gerber")
SOG = Manufacturer("SOG")
Emerson = Manufacturer("Emerson")
Franchi = Manufacturer("Franchi")
Winchester = Manufacturer("Winchester")
Mossberg = Manufacturer("Mossberg")
Benelli = Manufacturer("Benelli")
Remington = Manufacturer("Remington")
PGM = Manufacturer("PGM Precision")
Steyr = Manufacturer("Steyr Arms")
USA = Manufacturer("U.S. Military")
SBD = Manufacturer("Saab Bofors Dynamics")
GE = Manufacturer("General Electric")
NSV = Manufacturer("Nikitin-Sokolov-Volkov")
DS = Manufacturer("Degitarov-Shpagin")
Nammo = Manufacturer("Nammo")
Raytheon = Manufacturer("Raytheon")
GD = Manufacturer("General Dynamics")
AI = Manufacturer("Accuracy International")
BF = Manufacturer("Barret Firearms")
