<MainMenu>:
    FloatLayout:

        Button:
            background_normal: "D:/PythonProjects/MySqlConnector/pythonProject1/BETA_Projects/KIVY_PROJECT/images/heart_cut.png"
            background_down: "D:/PythonProjects/MySqlConnector/pythonProject1/BETA_Projects/KIVY_PROJECT/images/heart_cut.png"
            border: 0, 0, 0, 0
            size_hint: None, None
            size: 100, 100
            pos: 100, root.height - 150
            on_press: root.credits()

        BoxLayout:
            orientation: "vertical"
            spacing: 10
            padding: 10
            size_hint: 1, 1
            pos_hint: {"x": 0, "y": 0}

            Label:
                text: "MAIN MENU"
                font_size: 50
                color: 1, 0, 0, 1

            Button:
                text: "PLAY"
                font_size: 30
                on_press: root.play()

            Button:
                text: "SETTINGS"
                font_size: 30
                on_press: root.settings()

            Button:
                text: "QUIT"
                font_size: 30
                on_press: root.quit()


<Settings>:
    BoxLayout:
        orientation: "vertical"
        spacing: 10
        padding: 10

        Label:
            text: "SETTINGS"
            font_size: 50
            color: 1, 0, 0, 1

        Button:
            text: "TUTORIAL"
            font_size: 30
            on_press: root.tutorial()

        Button:
            text: "AUDIO"
            font_size: 30
            on_press: root.audio()

        Button:
            text: "BACK - MAIN MENU"
            font_size: 30
            on_press: root.from_settings_to_mm()


<Credits>:
    BoxLayout:
        orientation: "vertical"
        spacing: 10
        padding: 10

        Label:
            text: "CREDITS"
            font_size: 50
            color: 1, 0, 0, 1

        Label:
            text: "1. Egor Pavlenko - CEO"
            font_size: 35
            color: 1, 1, 1, 1

        Button:
            text: "BACK - MAIN MENU"
            font_size: 30
            on_press: root.from_credits_to_mm()
